volumes:
  wordpress_files:
    driver: local
    driver_opts:
      type: tmpfs
      device: /home/clsaad/data/wordpress-files
  wordpress_db:
    driver: local
    driver_opts:
      type: tmpfs
      device: /home/clsaad/data/wordpress-db

services:
  nginx:
    build: containers/nginx
    ports:
      - "443:443"
    networks:
      - 42_network
  wordpress:
    build: containers/wordpress
    networks:
      - 42_network
    volumes:
      - "wordpress_files:/var/www/html"

networks:
  42_network: {}