services:
  wordpress:
    build:
      context: containers/wordpress
      args:
        USER_NAME: ${USER_NAME}
        USER_PASSWORD: ${USER_PASSWORD}
    networks:
      - 42_network
    volumes:
      - wordpress_files:/var/www/html
    env_file:
      .env
    restart: unless-stopped
  mariadb:
    build: containers/mariadb
    networks:
      - 42_network
    volumes:
      - wordpress_db:/var/lib/mysql
    env_file:
      .env
    restart: unless-stopped
  nginx:
    build:
      context:
        containers/nginx
      args:
        DOCKER_TLS_CERTIFICATE: ${DOCKER_TLS_CERTIFICATE}
        DOCKER_TLS_KEY: ${DOCKER_TLS_KEY}
    ports:
      - "443:443"
    networks:
      - 42_network
    volumes:
      - wordpress_files:/var/www/html
    restart: unless-stopped

networks:
  42_network: {}

volumes:
  wordpress_files:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/clsaad/data/wordpress-files
  wordpress_db:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/clsaad/data/wordpress-db
